Minor bash.rc changes

diff --git a/bash.d/bashrc b/bash.d/bashrc
--- a/bash.d/bashrc
+++ b/bash.d/bashrc
@@ -7,7 +7,7 @@ BASH_ROOT=$HOME/bin-shared/bash.d
 # If not running interactively, don't do anything
 case $- in
     *i*) ;;
-      *) return;;
+    *) return;;
 esac
 
 # don't put duplicate lines or lines starting with space in the history.
@@ -39,10 +39,10 @@ fi
 
 # If this is an xterm set the title to user@host:dir
 case "$TERM" in
-xterm*|rxvt*)
-    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h \w\a\]$PS1"
+    xterm*|rxvt*)
+        PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h \w\a\]$PS1"
     ;;
-*)
+    *)
     ;;
 esac
 
@@ -65,130 +65,130 @@ fi
 # Detect the platform.
 case "$OSTYPE" in
 
-  solaris*)
+    solaris*)
     ;;
 
-  darwin*) # Mac (OSX)
+    darwin*) # Mac (OSX)
 
-    # Set LC encoding to UTF-8.
-    #export LC_ALL=en_GB.UTF-8
+        # Set LC encoding to UTF-8.
+        #export LC_ALL=en_GB.UTF-8
 
-    # Fixes for illegal byte sequence (http://stackoverflow.com/q/19242275/55075).
-    export LC_ALL=C
-    export LANG=C
+        # Fixes for illegal byte sequence (http://stackoverflow.com/q/19242275/55075).
+        export LC_ALL=C
+        export LANG=C
 
-    # For MAMP (OSX)
-    PHP_VER="5.6.20" # Or: 5.4.19/5.5.3 ($ls /Applications/MAMP/bin/php/php*)
+        # For MAMP (OSX)
+        PHP_VER="5.6.20" # Or: 5.4.19/5.5.3 ($ls /Applications/MAMP/bin/php/php*)
 
-    # Mule ESB configuration.
-    export MULE_HOME=/usr/local/opt/mule
-    [ -d "$MULE_HOME" ] && export PATH=$PATH:$MULE_HOME/bin
+        # Mule ESB configuration.
+        export MULE_HOME=/usr/local/opt/mule
+        [ -d "$MULE_HOME" ] && export PATH=$PATH:$MULE_HOME/bin
 
-    # Set PATH for OSX
-    export PATH="$HOME/bin:$HOME/binfiles:/usr/local/sbin:/usr/local/bin:$PATH"
-    type brew > /dev/null && brew --prefix homebrew/php/php56 > /dev/null && export PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"
-    export PATH="$PATH:/Applications/MAMP/Library/bin:/Applications/MAMP/bin/php/php$PHP_VER/bin:/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin/gcc"
-    export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH" # add a "gnubin" for coreutils
-    export PYTHONPATH="$PYTHONPATH:$HOME/.python" # /usr/local/lib/python3.4/site-packages"
-    # :/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
+        # Set PATH for OSX
+        export PATH="$HOME/bin:$HOME/binfiles:/usr/local/sbin:/usr/local/bin:$PATH"
+        type brew > /dev/null && brew --prefix homebrew/php/php56 > /dev/null && export PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"
+        export PATH="$PATH:/Applications/MAMP/Library/bin:/Applications/MAMP/bin/php/php$PHP_VER/bin:/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin/gcc"
+        export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH" # add a "gnubin" for coreutils
+        export PYTHONPATH="$PYTHONPATH:$HOME/.python" # /usr/local/lib/python3.4/site-packages"
+        # :/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
 
-    # Development variables.
-    export FLEX_HOME="/usr/local/Cellar/flex_sdk/4.6.0.23201/libexec"
-    export DYLD_FALLBACK_LIBRARY_PATH="/usr/X11/lib:/usr/lib" # See: http://stackoverflow.com/questions/10820981/dylibs-and-os-x
-    #export PHP_AUTOCONF="$(which autoconf)" # Install autoconf, which is needed for the installation of phpMyAdmin.
+        # Development variables.
+        export FLEX_HOME="/usr/local/Cellar/flex_sdk/4.6.0.23201/libexec"
+        export DYLD_FALLBACK_LIBRARY_PATH="/usr/X11/lib:/usr/lib" # See: http://stackoverflow.com/questions/10820981/dylibs-and-os-x
+        #export PHP_AUTOCONF="$(which autoconf)" # Install autoconf, which is needed for the installation of phpMyAdmin.
 
-    # Fix for Git-SVN (OSX) [Error: Can't locate SVN/Core.pm in @INC]. See: http://stackoverflow.com/questions/13571944/git-svn-unrecognized-url-scheme-error
-    export PERL5LIB="$HOME/perl5/lib/perl5:/Applications/Xcode.app/Contents/Developer/Library/Perl/5.16"
+        # Fix for Git-SVN (OSX) [Error: Can't locate SVN/Core.pm in @INC]. See: http://stackoverflow.com/questions/13571944/git-svn-unrecognized-url-scheme-error
+        export PERL5LIB="$HOME/perl5/lib/perl5:/Applications/Xcode.app/Contents/Developer/Library/Perl/5.16"
 
-    # OSX specific aliases.
-    alias diffmerge="/Applications/DiffMerge.app/Contents/MacOS/DiffMerge"
-    alias xt-files="egrep -o '/[^/]+:[0-9]+'"
-    alias iphone="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications/iPhone Simulator.app/Contents/MacOS/iPhone Simulator" # OSX Lion
+        # OSX specific aliases.
+        alias diffmerge="/Applications/DiffMerge.app/Contents/MacOS/DiffMerge"
+        alias xt-files="egrep -o '/[^/]+:[0-9]+'"
+        alias iphone="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications/iPhone Simulator.app/Contents/MacOS/iPhone Simulator" # OSX Lion
 
-    # Set prompt
-    export GIT_PS="\[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\] "
-    export PS1="\[\033[01;31m\]\u\[\033[01;33m\]@\[\033[01;36m\]\h \[\033[01;33m\]\W \[\033[01;35m\]\$ $GIT_PS\[\033[00m\]"
+        # Set prompt
+        export GIT_PS="\[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\] "
+        export PS1="\[\033[01;31m\]\u\[\033[01;33m\]@\[\033[01;36m\]\h \[\033[01;33m\]\W \[\033[01;35m\]\$ $GIT_PS\[\033[00m\]"
 
-    # Set other options.
-    export LS_OPTIONS='-G -h'
+        # Set other options.
+        export LS_OPTIONS='-G -h'
 
-    # OSX: Enable bash_completion (Install by: brew install bash-completion)
-    #       Homebrew's own bash completion script: /usr/local/etc/bash_completion.d
-    if [ -f $(brew --prefix)/etc/bash_completion ]; then
-      . $(brew --prefix)/etc/bash_completion
-    fi
+        # OSX: Enable bash_completion (Install by: brew install bash-completion)
+        #       Homebrew's own bash completion script: /usr/local/etc/bash_completion.d
+        if [ -f $(brew --prefix)/etc/bash_completion ]; then
+            . $(brew --prefix)/etc/bash_completion
+        fi
 
     ;;
 
-  linux-gnu*) # Debian
+    linux-gnu*) # Debian
 
-    # Debian specific
-    # set variable identifying the chroot you work in (used in the prompt below)
-    if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
-      debian_chroot=$(cat /etc/debian_chroot)
-    fi
+        # Debian specific
+        # set variable identifying the chroot you work in (used in the prompt below)
+        if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
+            debian_chroot=$(cat /etc/debian_chroot)
+        fi
 
 
-    if [ "$color_prompt" = yes ]; then
-      PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
-    else
-      PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
-    fi
+        if [ "$color_prompt" = yes ]; then
+            PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
+        else
+            PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
+        fi
 
-    # If this is an xterm set the title to user@host:dir
-    case "$TERM" in
-    xterm*|rxvt*)
-      PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
-      ;;
-    *)
-      ;;
-    esac
+        # If this is an xterm set the title to user@host:dir
+        case "$TERM" in
+            xterm*|rxvt*)
+                PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
+            ;;
+            *)
+            ;;
+        esac
 
     ;;& # fall-through syntax requires bash >= 4; (OSX, check: http://apple.stackexchange.com/q/141752/22781)
 
-  linux*)
-    # Set LC encoding to UTF-8.
-    # Ubuntu way: Use locale-gen (part of locales).
-    export LANG=en_US.UTF-8
-    export LANGUAGE="en_US:en"
+    linux*)
+        # Set LC encoding to UTF-8.
+        # Ubuntu way: Use locale-gen (part of locales).
+        export LANG=en_US.UTF-8
+        export LANGUAGE="en_US:en"
 
-    # Set PATH for Linux
-    export PATH=/usr/local/bin:$PATH:/opt/local/bin:${HOME}/bin
-    export PATH=$PATH:${HOME}/.local/share/flatpak/exports/bin
+        # Set PATH for Linux
+        export PATH=/usr/local/bin:$PATH:/opt/local/bin:${HOME}/bin
+        export PATH=$PATH:${HOME}/.local/share/flatpak/exports/bin
 
-    # Linux: enable color support of ls and also add handy aliases
-    if [ -x /usr/bin/dircolors ]; then
-        test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
-    fi
+        # Linux: enable color support of ls and also add handy aliases
+        if [ -x /usr/bin/dircolors ]; then
+            test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
+        fi
 
-    # Linux: Enable bash_completion (Install by: brew install bash-completion)
-    # enable programmable completion features (you don't need to enable
-    # this, if it's already enabled in /etc/bash.bashrc and /etc/profile
-    # sources /etc/bash.bashrc).
-    # Install by: sudo apt-get install bash-completion
-    if ! shopt -oq posix; then
-      if [ -f /usr/share/bash-completion/bash_completion ]; then
-        . /usr/share/bash-completion/bash_completion
-      elif [ -f /etc/bash_completion ]; then
-        . /etc/bash_completion
-      fi
-    fi
+        # Linux: Enable bash_completion (Install by: brew install bash-completion)
+        # enable programmable completion features (you don't need to enable
+        # this, if it's already enabled in /etc/bash.bashrc and /etc/profile
+        # sources /etc/bash.bashrc).
+        # Install by: sudo apt-get install bash-completion
+        if ! shopt -oq posix; then
+            if [ -f /usr/share/bash-completion/bash_completion ]; then
+                . /usr/share/bash-completion/bash_completion
+                elif [ -f /etc/bash_completion ]; then
+                . /etc/bash_completion
+            fi
+        fi
 
-    # Linux aliases
-    # Add an "alert" alias for long running commands. Use like so: sleep 10; alert
-    alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
+        # Linux aliases
+        # Add an "alert" alias for long running commands. Use like so: sleep 10; alert
+        alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
 
-    # Set other options.
-    export LS_OPTIONS='--color=auto -h'
+        # Set other options.
+        export LS_OPTIONS='--color=auto -h'
 
     ;;
 
-  bsd*)
-    export LS_OPTIONS='-G'
+    bsd*)
+        export LS_OPTIONS='-G'
     ;;
 
-  *)
-    echo "Unknown: $OSTYPE"
+    *)
+        echo "Unknown: $OSTYPE"
     ;;
 esac
 
@@ -206,15 +206,15 @@ fi
 # this, if it's already enabled in /etc/bash.bashrc and /etc/profile
 # sources /etc/bash.bashrc).
 if ! shopt -oq posix; then
-  if [ -f /usr/share/bash-completion/bash_completion ]; then
-    . /usr/share/bash-completion/bash_completion
-  elif [ -f /etc/bash_completion ]; then
-    . /etc/bash_completion
-  fi
+    if [ -f /usr/share/bash-completion/bash_completion ]; then
+        . /usr/share/bash-completion/bash_completion
+        elif [ -f /etc/bash_completion ]; then
+        . /etc/bash_completion
+    fi
 fi
 
 if [ -x /usr/bin/mint-fortune ]; then
-     /usr/bin/mint-fortune
+    /usr/bin/mint-fortune
 fi
 
 unset color_prompt force_color_prompt
@@ -236,24 +236,28 @@ GIT_PROMPT_ONLY_IN_REPO=1
 source ~/bin-shared/bin/bash-git-prompt/gitprompt.sh
 
 if  [ -x "$(command -v vim)" ]; then
-  export VISUAL=vim
-  export EDITOR="$VISUAL"
+    export VISUAL=vim
+    export EDITOR="$VISUAL"
 fi
 
 # Display a much more detailed info about the system
 if  [ -x "$(command -v inxi)" ]; then
-  inxi -F
+    inxi -F
 fi
 
-if  [ -x "$(command -v neofetch)" ]; then
-    neofetch
+if  [ -x "$(command -v fastfetch)" ]; then
+    fastfetch
 else
-	# Fall back onto screen fetch if we must.
-  if  [ -x "$(command -v screenfetch)" ]; then
- 		screenfetch
-	else
-		echo Did not find neofetch or screenfetch
-	fi
+    if  [ -x "$(command -v fastfetch)" ]; then
+        neofetch
+    else
+        # Fall back onto screen fetch if we must.
+        if  [ -x "$(command -v screenfetch)" ]; then
+            screenfetch
+        else
+            echo Did not find neofetch or screenfetch
+        fi
+    fi
 fi
 
 # PS1="\h_\u[\!]\$ "
@@ -272,5 +276,5 @@ Checkmark='\342\234\223'
 export GIT_PS1_SHOWDIRTYSTATE=1
 export GIT_PS1_SHOWUNTRACKEDFILES=1
 # only do this for interactive sessions
-    # source ~/.git_prompt.sh
-    PS1="$Red\u$Blue@$Red\h$Green \w$Reset \$(__git_ps1 ' (%s)')$Blue[\!]\n\$ $Reset"
+# source ~/.git_prompt.sh
+PS1="$Red\u$Blue@$Red\h$Green \w$Reset \$(__git_ps1 ' (%s)')$Blue[\!]\n\$ $Reset"
